"""Added account table

Revision ID: 71181dbdf3fa
Revises: 6501061e929a
Create Date: 2024-01-04 13:51:38.241221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71181dbdf3fa'
down_revision = '6501061e929a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
