"""Added update

Revision ID: f25507bd0fd6
Revises: 71181dbdf3fa
Create Date: 2024-01-04 13:55:00.458611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25507bd0fd6'
down_revision = '71181dbdf3fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
